name: marvel_icons

description: "A learn through Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  intl:
  cached_network_image:
  crypto: ^3.0.6
  provider: ^6.1.2
  # flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dark_icon.png
    - assets/images/light_icon.png
    - assets/images/iron_man_gs.png
    - assets/images/wp/1.jpg
    - assets/images/wp/2.jpg
    - assets/images/wp/3.jpg
    - assets/images/wp/4.jpg
    - assets/images/wp/5.jpg
    - assets/images/wp/6.jpg
